// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  styleUrls: ['./app.component.scss'],
  templateUrl: './app.component.html',
})
export class AppComponent {
  public title = 'Symphony';
}

<div class="grid h-screen">
  <app-toolbar [name]="name | async"></app-toolbar>
  <app-dashboard
    [name]="name | async"
    (nameChanged)="setName($event)"
  ></app-dashboard>
</div>

// vue/src/components/App.vue
<template>
  <div class="grid h-screen" id="main">
    <Toolbar />
    <Dashboard />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Dashboard from "./Dashboard.vue";
import Toolbar from "./Toolbar.vue";

export default defineComponent({
  components: { Dashboard, Toolbar },
  name: "App",
});
</script>
