// react/parcel/src/components/Dashboard.tsx
import * as React from "react";

interface Props {
  name: string;
  setName: (value: string) => void;
}

const Dashboard = ({ name, setName }: Props) => {
  return (
    <div className="flex items-center justify-center text-blue-200">
      <div className="grid">
        <h1 className="text-lg pb-2">Welcome {name} to the dashboard!</h1>
        <button onClick={() => setName("Chat")}>Change Name</button>
      </div>
    </div>
  );
};

export default Dashboard;

// angular/src/app/dashboard/dashboard.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss'],
})
export class DashboardComponent {
  @Input()
  public name: string;

  @Output()
  public nameChanged = new EventEmitter<string>();

  public setName(name: string) {
    this.nameChanged.emit(name);
  }
}

<div class="flex items-center justify-center text-blue-200">
  <div class="grid">
    <h1 class="text-lg pb-2">Welcome to the dashboard {{ name }}!</h1>
    <button (click)="setName('Chat')">Change Name</button>
  </div>
</div>
