// angular/src/app/toolbar/toolbar.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-toolbar',
  templateUrl: './toolbar.component.html',
  styleUrls: ['./toolbar.component.scss'],
})
export class ToolbarComponent {
  @Input()
  public name: string;
}

<div class="bg-black grid grid-cols-7 p-2">
  <h1 class="col-start-7 text-xl text-white text-center">Hello {{ name }}</h1>
</div>

// vue-webpack/src/components/Toolbar.vue
<template>
  <div class="bg-black grid grid-cols-7 p-2">
    <h1 class="col-start-7 text-xl text-white text-center">Hello {{ name }}</h1>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { UserStore } from "../stores/user";

export default defineComponent({
  components: {},
  computed: { name: () => UserStore.state.name },
  name: "Toolbar",
});
</script>
