// vue-webpack/src/components/Dashboard.vue
<template>
  <div class="flex items-center justify-center text-blue-200">
    <div class="grid">
      <h1 class="text-lg pb-2">Welcome to the dashboard {{ name }}!</h1>
      <button @click="setName('Chat')">Change Name</button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { UserStore } from "../stores/user";

const { setName } = UserStore;

export default defineComponent({
  components: {},
  computed: { name: () => UserStore.state.name },
  methods: { setName },
  name: "Dashboard",
});
</script>

// react/parcel/src/components/Dashboard.tsx
import * as React from "react";

interface Props {
  name: string;
  setName: (value: string) => void;
}

const Dashboard = ({ name, setName }: Props) => {
  return (
    <div className="flex items-center justify-center text-blue-200">
      <div className="grid">
        <h1 className="text-lg pb-2">Welcome {name} to the dashboard!</h1>
        <button onClick={() => setName("Chat")}>Change Name</button>
      </div>
    </div>
  );
};

export default Dashboard;
