// react/parcel/src/components/Dashboard.tsx
import * as React from "react";

interface Props {
  name: string;
  setName: (value: string) => void;
}

const Dashboard = ({ name, setName }: Props) => {
  return (
    <div className="flex items-center justify-center text-blue-200">
      <div className="grid">
        <h1 className="text-lg pb-2">Welcome {name} to the dashboard!</h1>
        <button onClick={() => setName("Chat")}>Change Name</button>
      </div>
    </div>
  );
};

export default Dashboard;

// svelte-parcel/src/components/Dashboard.svelte
<script lang="ts">
  import type { Writable } from "svelte/store";

  export let nameStore: Writable<string>;

  function setName(name: string) {
    $nameStore = name;
  }

  $: p = new Promise((resolve) => setTimeout(() => resolve($nameStore), 1000));
</script>

<div class="flex items-center justify-center text-blue-200">
  <div class="grid">
    <h1 class="text-lg pb-2">Welcome to the dashboard {$nameStore}!</h1>

    {#await p}
      <p>...waiting</p>
    {:then value}
      <p>The value is {value}</p>
    {:catch error}
      <p style="color: red">{error.message}</p>
    {/await}

    <button on:click={() => setName('Chat')}>Change Name</button>
  </div>
</div>
